(function(){
var menu=document.querySelector('[data-menu-toggle]');
var mobile=document.querySelector('[data-mobile-nav]');
if(menu&&mobile){menu.addEventListener('click',function(){mobile.classList.toggle('open')})}
var topBtn=document.querySelector('[data-to-top]');
if(topBtn){window.addEventListener('scroll',function(){topBtn.classList.toggle('show',window.scrollY>500)});topBtn.addEventListener('click',function(){window.scrollTo({top:0,behavior:'smooth'})})}
var hero=document.querySelector('[data-hero]');
if(hero){var slides=[].slice.call(hero.querySelectorAll('[data-hero-slide]'));var dots=[].slice.call(hero.querySelectorAll('[data-hero-dot]'));var active=0;var show=function(i){if(!slides.length)return;active=(i+slides.length)%slides.length;slides.forEach(function(s,n){s.classList.toggle('active',n===active)});dots.forEach(function(d,n){d.classList.toggle('active',n===active)})};dots.forEach(function(d){d.addEventListener('click',function(){show(parseInt(d.getAttribute('data-hero-dot')||'0',10))})});if(slides.length>1){setInterval(function(){show(active+1)},5200)}}
var normalize=function(v){return (v||'').toString().trim().toLowerCase()};
document.querySelectorAll('[data-search-scope]').forEach(function(scope){var input=scope.querySelector('[data-search-input]');var cards=[].slice.call(scope.querySelectorAll('[data-card]'));var activeFilter='all';var apply=function(){var q=normalize(input?input.value:'');cards.forEach(function(card){var text=normalize([card.dataset.title,card.dataset.year,card.dataset.region,card.dataset.type,card.dataset.genre,card.dataset.category].join(' '));var okText=!q||text.indexOf(q)>-1;var okFilter=activeFilter==='all'||text.indexOf(normalize(activeFilter))>-1;card.classList.toggle('hidden-card',!(okText&&okFilter))})};if(input){input.addEventListener('input',apply)}scope.querySelectorAll('[data-filter]').forEach(function(btn){btn.addEventListener('click',function(){scope.querySelectorAll('[data-filter]').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');activeFilter=btn.getAttribute('data-filter')||'all';apply()})});apply()});
function startPlayer(box){var video=box.querySelector('video[data-play]');if(!video)return;var src=video.getAttribute('data-play');if(!src)return;if(!video.dataset.ready){if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=src}else if(window.Hls&&window.Hls.isSupported()){var hls=new Hls({enableWorker:true,lowLatencyMode:true});hls.loadSource(src);hls.attachMedia(video);video._hls=hls}else{video.src=src}video.dataset.ready='1'}box.classList.add('playing');var p=video.play();if(p&&p.catch){p.catch(function(){})}}
document.querySelectorAll('.player-wrap').forEach(function(box){var btn=box.querySelector('[data-play-button]');var video=box.querySelector('video');if(btn){btn.addEventListener('click',function(){startPlayer(box)})}if(video){video.addEventListener('click',function(){if(!video.dataset.ready||video.paused){startPlayer(box)}});video.addEventListener('play',function(){box.classList.add('playing')})}})
})();
